sudo: false
dist: trusty
language: php
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
matrix:
  include:
    - php: 7.3
      env: UNIT=1 PHPLINT=1 PHPCS=1 COVERAGE=1
    - php: 7.0
      env: UNIT=1 PHPLINT=1
      dist: trusty
    - php: 7.3
      env: INTEGRATION=1 WP_VERSION=latest
    - php: 7.0
      env: INTEGRATION=1 WP_VERSION=latest
      dist: trusty
    - php: 7.3
      env: INTEGRATION=1 WP_VERSION=4.7
    - php: 7.0
      env: INTEGRATION=1 WP_VERSION=4.7
      dist: trusty
    - php: nightly
      env: UNIT=1
    - php: 7.3
      env: INTEGRATION=1 WP_VERSION=master
  allow_failures:
    - php: nightly
      env: UNIT=1
    - php: 7.3
      env: INTEGRATION=1 WP_VERSION=master
before_install:
  - |
    if [[ "$COVERAGE" != "1" ]]; then
      stable='^[0-9\.]+$'
      if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
        phpenv config-rm xdebug.ini
      fi
    fi
  - |
    case "$TRAVIS_PHP_VERSION" in
      5.6|5.5|5.4|5.3)
        composer global require "phpunit/phpunit:^4"
        composer install
        PHPUNIT_BIN="phpunit"
        ;;
      5.2)
        PHPUNIT_BIN="phpunit"
        ;;
      *)
        composer install
        PHPUNIT_BIN="vendor/bin/phpunit"
        ;;
    esac
before_script:
  - |
    if [[ "$INTEGRATION" == "1" ]]; then
      if [[ "$WP_VERSION" == "latest" ]]; then
        curl -s http://api.wordpress.org/core/version-check/1.7/ > /tmp/wp-latest.json
        WP_VERSION=$(grep -o '"version":"[^"]*' /tmp/wp-latest.json | sed 's/"version":"//')
      fi
      PLUGIN_SLUG=$(basename $(pwd))
      export WP_DEVELOP_DIR=/tmp/wordpress/
      git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
      cd ..
      cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
      cd /tmp/wordpress/
      cp wp-tests-config-sample.php wp-tests-config.php
      sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
      sed -i "s/yourusernamehere/travis/" wp-tests-config.php
      sed -i "s/yourpasswordhere//" wp-tests-config.php
      mysql -e "CREATE DATABASE wordpress_tests;" -uroot
      cd "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"
    fi
  - phpenv rehash
script:
  - |
    if [[ "$PHPLINT" == "1" ]]; then
      composer run-script phplint
    fi
  - |
    if [[ "$PHPCS" == "1" ]]; then
      composer run-script phpcs
    fi
  - |
    if [[ "$UNIT" == "1" ]]; then
      if [[ "$COVERAGE" == "1" ]]; then
        mkdir -p tests/logs
        $PHPUNIT_BIN --coverage-clover tests/logs/clover.xml
      else
        $PHPUNIT_BIN
      fi
    fi
  - |
    if [[ "$INTEGRATION" == "1" ]]; then
      if [[ "$COVERAGE" == "1" ]]; then
        mkdir -p tests/logs
        $PHPUNIT_BIN -c phpunit-integration.xml.dist --coverage-clover tests/logs/clover.xml
      else
        $PHPUNIT_BIN -c phpunit-integration.xml.dist
      fi
    fi
notifications:
  email: false